volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - kittygram-net
  backend:
    image: bobah2060/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/backend_media
    init: true 
    networks:
      - kittygram-net
    ports:
      - "9000:9000"
    depends_on:
      - db
  frontend:
    env_file: .env
    image: bobah2060/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    networks:
      - kittygram-net
  gateway:
    image: bobah2060/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    networks:
      - kittygram-net
    depends_on:
      - backend
    volumes:
      - static:/staticfiles
      - media:/mediafiles

networks:
  kittygram-net:
    driver: bridge
